package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	_ "github.com/lib/pq"
)

type JobSeed struct {
	ID             string
	Title          string
	Department     string
	Level          string
	Location       string
	EmploymentType string
	SalaryMin      int
	SalaryMax      int
	Currency       string
	Description    string
	Requirements   string
	Benefits       string
	Status         string
	AISummary      string
}

func main() {
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		log.Fatal("DATABASE_URL not set")
	}

	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		log.Fatalf("Failed to ping database: %v", err)
	}

	companyID := "aaaaaaaa-0000-0000-0000-000000000001"
	createdBy := "bbbbbbbb-0000-0000-0000-000000000002"

	jobs := []JobSeed{
		{
			ID:             "cccccccc-0000-0000-0000-000000000001",
			Title:          "Frontend Developer (VueJS)",
			Department:     "Engineering",
			Level:          "middle",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      18000000,
			SalaryMax:      30000000,
			Currency:       "VND",
			Description:    "Phát triển giao diện người dùng cho nền tảng SaaS bằng Vue 3 + Vite. Phối hợp với team backend và thiết kế để hoàn thiện trải nghiệm.",
			Requirements:   "Thành thạo Vue 3, JavaScript ES6+, HTML/CSS. Kinh nghiệm 2+ năm. Biết Pinia, Vue Router. Ưu tiên có kinh nghiệm TypeScript.",
			Benefits:       "Lương tháng 13, bảo hiểm đầy đủ, làm việc hybrid, review lương 2 lần/năm.",
			Status:         "open",
			AISummary:      "Vị trí Frontend middle tập trung Vue 3, phù hợp ứng viên 2-4 năm kinh nghiệm SPA.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000002",
			Title:          "Backend Engineer (Go)",
			Department:     "Engineering",
			Level:          "senior",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      30000000,
			SalaryMax:      50000000,
			Currency:       "VND",
			Description:    "Thiết kế và xây dựng microservices bằng Go, PostgreSQL, Redis. Chịu trách nhiệm hiệu năng và độ tin cậy hệ thống realtime.",
			Requirements:   "Thành thạo Go, PostgreSQL, thiết kế API. Hiểu concurrency, message queue. Kinh nghiệm 4+ năm backend.",
			Benefits:       "ESOP, laptop cấu hình cao, ngân sách học tập 10 triệu/năm.",
			Status:         "open",
			AISummary:      "Backend senior Go cho hệ thống realtime, đòi hỏi kinh nghiệm concurrency và tối ưu hiệu năng.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000003",
			Title:          "Data Scientist (AI/ML)",
			Department:     "Data",
			Level:          "middle",
			Location:       "TP. Hồ Chí Minh",
			EmploymentType: "full_time",
			SalaryMin:      25000000,
			SalaryMax:      40000000,
			Currency:       "VND",
			Description:    "Xây dựng mô hình ML phục vụ gợi ý và phân tích dữ liệu tuyển dụng. Làm việc với Python, scikit-learn, và LLM.",
			Requirements:   "Thành thạo Python, pandas, scikit-learn. Kiến thức thống kê vững. Ưu tiên có kinh nghiệm NLP/LLM.",
			Benefits:       "Chế độ remote linh hoạt, thưởng theo dự án.",
			Status:         "open",
			AISummary:      "Data Scientist middle, trọng tâm ML + NLP cho sản phẩm tuyển dụng AI.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000005",
			Title:          "Senior ReactJS / Next.js Engineer",
			Department:     "Engineering",
			Level:          "senior",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      28000000,
			SalaryMax:      45000000,
			Currency:       "VND",
			Description:    "Xây dựng giao diện ứng dụng web tốc độ cao sử dụng Next.js 14 Server Components, React Query và Tailwind CSS.",
			Requirements:   "4+ năm kinh nghiệm với React/Next.js, TypeScript, Zustand/Redux. Am hiểu Server Side Rendering và Core Web Vitals.",
			Benefits:       "Thưởng KPI theo quý, bảo hiểm sức khỏe PVI, Macbook Pro M3.",
			Status:         "open",
			AISummary:      "Ứng viên Senior React/Next.js có năng lực tối ưu SSR và giao diện mượt mà.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000006",
			Title:          "Senior Python AI / LLM Engineer",
			Department:     "Artificial Intelligence",
			Level:          "senior",
			Location:       "Remote",
			EmploymentType: "full_time",
			SalaryMin:      40000000,
			SalaryMax:      70000000,
			Currency:       "VND",
			Description:    "Tích hợp các mô hình ngôn ngữ lớn (Gemini, OpenAI, Llama 3) vào hệ thống Agentic Workflow, fine-tuning và RAG.",
			Requirements:   "Thành thạo Python, FastAPI, LangChain / LlamaIndex, Vector Database (Qdrant, Pinecone). 3+ năm kinh nghiệm AI/ML.",
			Benefits:       "Làm việc Remote 100%, ngân sách trợ cấp thiết bị làm việc 20 triệu.",
			Status:         "open",
			AISummary:      "Kỹ sư AI/LLM chuyên sâu xây dựng trợ lý thông minh và hệ thống RAG.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000007",
			Title:          "Lead Golang Microservices Architect",
			Department:     "Engineering",
			Level:          "lead",
			Location:       "TP. Hồ Chí Minh",
			EmploymentType: "full_time",
			SalaryMin:      45000000,
			SalaryMax:      80000000,
			Currency:       "VND",
			Description:    "Định hướng kiến trúc hệ thống distributed microservices chịu tải hàng triệu request/ngày bằng Go, gRPC và NATS.",
			Requirements:   "6+ năm kinh nghiệm Backend, 4+ năm với Golang. Nắm vững Domain-Driven Design (DDD), Distributed Tracing, Kafka/NATS.",
			Benefits:       "Cổ phiếu ESOP, du lịch nước ngoài hàng năm, chế độ chăm sóc gia đình cao cấp.",
			Status:         "open",
			AISummary:      "Vị trí Tech Lead/Architect Golang đòi hỏi tầm nhìn hệ thống quy mô lớn.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000008",
			Title:          "Mobile Developer (Flutter / React Native)",
			Department:     "Engineering",
			Level:          "middle",
			Location:       "Đà Nẵng",
			EmploymentType: "full_time",
			SalaryMin:      16000000,
			SalaryMax:      28000000,
			Currency:       "VND",
			Description:    "Phát triển ứng dụng di động đa nền tảng cho người dùng tìm việc và nhà tuyển dụng trên iOS và Android.",
			Requirements:   "2+ năm kinh nghiệm với Flutter hoặc React Native. Đã từng public ứng dụng lên App Store / Google Play Store.",
			Benefits:       "Môi trường làm việc năng động gần biển Đà Nẵng, hỗ trợ chi phí di chuyển.",
			Status:         "open",
			AISummary:      "Lập trình viên Mobile Middle thành thạo cross-platform Flutter/React Native.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000009",
			Title:          "UI/UX & Product Designer",
			Department:     "Product & Design",
			Level:          "middle",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      18000000,
			SalaryMax:      32000000,
			Currency:       "VND",
			Description:    "Thực hiện nghiên cứu người dùng, thiết kế wireframe, prototype và Design System hoàn chỉnh trên Figma cho Web & App.",
			Requirements:   "Thành thạo Figma, Adobe CC. Có Portfolio ấn tượng về giao diện SaaS/Mobile. Hiểu biết về Usability Testing.",
			Benefits:       "Trang bị màn hình 4K, môi trường sáng tạo tự do, trà cà phê bánh ngọt mỗi ngày.",
			Status:         "open",
			AISummary:      "Product Designer có gu thẩm mỹ hiện đại, tập trung vào trải nghiệm người dùng cao cấp.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000010",
			Title:          "Product Manager (SaaS Platform)",
			Department:     "Product",
			Level:          "senior",
			Location:       "TP. Hồ Chí Minh",
			EmploymentType: "full_time",
			SalaryMin:      35000000,
			SalaryMax:      60000000,
			Currency:       "VND",
			Description:    "Quản lý vòng đời sản phẩm SaaS tuyển dụng AI, lên lộ trình Product Roadmap, phân tích Metric (ARR, Churn, Retention).",
			Requirements:   "4+ năm kinh nghiệm Product Manager sản phẩm B2B SaaS. Tư duy Data-driven, thành thạo Mixpanel, Agile/Scrum.",
			Benefits:       "Thưởng năm hấp dẫn theo tăng trưởng doanh thu, bảo hiểm gia đình cao cấp.",
			Status:         "open",
			AISummary:      "Product Manager dày dặn kinh nghiệm thúc đẩy sản phẩm SaaS tăng trưởng.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000011",
			Title:          "Senior QA Automation Engineer",
			Department:     "Quality Assurance",
			Level:          "senior",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      22000000,
			SalaryMax:      36000000,
			Currency:       "VND",
			Description:    "Xây dựng kịch bản kiểm thử tự động cho E2E Testing và API Testing bằng Cypress / Playwright và Postman/K6.",
			Requirements:   "3+ năm kinh nghiệm Automation Test, thành thạo JavaScript/TypeScript hoặc Python. Biết tích hợp CI/CD pipeline.",
			Benefits:       "Lương tháng 13, phụ cấp thi chứng chỉ ISTQB, làm việc 5 ngày/tuần.",
			Status:         "open",
			AISummary:      "Kỹ sư QA Automation chuyên nghiệp đảm bảo chất lượng phần mềm tự động.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000012",
			Title:          "Senior DevOps Engineer (AWS & K8s)",
			Department:     "Infrastructure",
			Level:          "senior",
			Location:       "Remote",
			EmploymentType: "full_time",
			SalaryMin:      35000000,
			SalaryMax:      65000000,
			Currency:       "VND",
			Description:    "Quản lý hạ tầng Kubernetes Cluster trên AWS EKS, thiết lập CI/CD GitHub Actions, ArgoCD, Prometheus & Grafana.",
			Requirements:   "4+ năm kinh nghiệm DevOps/SRE, thành thạo Terraform, Docker, Kubernetes, Helm. Có chứng chỉ AWS Certified DevOps.",
			Benefits:       "Chế độ Remote tự do địa điểm, thưởng chứng chỉ quốc tế.",
			Status:         "open",
			AISummary:      "Kỹ sư DevOps Senior làm chủ hạ tầng Cloud Native và tự động hóa CI/CD.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000013",
			Title:          "Data Engineer (Spark & Snowflake)",
			Department:     "Data",
			Level:          "senior",
			Location:       "TP. Hồ Chí Minh",
			EmploymentType: "full_time",
			SalaryMin:      32000000,
			SalaryMax:      55000000,
			Currency:       "VND",
			Description:    "Thiết kế và vận hành luồng ETL/ELT xử lý dữ liệu lớn bằng Apache Airflow, PySpark, Snowflake và dbt.",
			Requirements:   "3+ năm kinh nghiệm Data Engineering, giỏi SQL và Python. Hiểu biết sâu về Data Lakehouse và Data Modeling.",
			Benefits:       "Chế độ chăm sóc sức khỏe cao cấp, thưởng dự án theo quý.",
			Status:         "open",
			AISummary:      "Data Engineer có khả năng xử lý Big Data và xây dựng Data Pipeline quy mô lớn.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000014",
			Title:          "Junior Data Analyst (BI & SQL)",
			Department:     "Data",
			Level:          "junior",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      11000000,
			SalaryMax:      18000000,
			Currency:       "VND",
			Description:    "Truy vấn dữ liệu báo cáo kinh doanh, thiết kế Dashboard trực quan hóa trên Power BI / Tableau cho Ban giám đốc.",
			Requirements:   "1+ năm kinh nghiệm Data Analysis, giỏi SQL, Excel nâng cao. Tư duy logic và khả năng phân tích dữ liệu tốt.",
			Benefits:       "Được đào tạo trực tiếp từ Data Director, hỗ trợ khóa học nâng cao nghiệp vụ.",
			Status:         "open",
			AISummary:      "Data Analyst Junior nhanh nhạy với con số và sử dụng thành thạo SQL/PowerBI.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000015",
			Title:          "Node.js / NestJS Backend Developer",
			Department:     "Engineering",
			Level:          "middle",
			Location:       "TP. Hồ Chí Minh",
			EmploymentType: "full_time",
			SalaryMin:      20000000,
			SalaryMax:      35000000,
			Currency:       "VND",
			Description:    "Phát triển các mô-đun API RESTful và WebSocket phục vụ tính năng phỏng vấn và chấm điểm AI bằng NestJS & TypeScript.",
			Requirements:   "2+ năm kinh nghiệm Node.js/NestJS, PostgreSQL, Redis, Socket.io. Hiểu về Clean Architecture và SOLID.",
			Benefits:       "Review lương 6 tháng/lần, team building tại các resort 5 sao.",
			Status:         "open",
			AISummary:      "Backend Developer chuyên NestJS & TypeScript phát triển API hiệu năng cao.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000016",
			Title:          "Fullstack Engineer (React + Node.js)",
			Department:     "Engineering",
			Level:          "middle",
			Location:       "Remote",
			EmploymentType: "full_time",
			SalaryMin:      24000000,
			SalaryMax:      42000000,
			Currency:       "VND",
			Description:    "Xây dựng tính năng trọn gói từ Frontend ReactJS đến Backend Node.js/Express cho phân hệ nhà tuyển dụng.",
			Requirements:   "3+ năm kinh nghiệm Fullstack, sử dụng thành thạo React, Node.js, PostgreSQL/MongoDB. Có khả năng tự chủ công việc.",
			Benefits:       "Thời gian làm việc linh hoạt, thưởng hiệu suất hàng tháng.",
			Status:         "open",
			AISummary:      "Fullstack Engineer đa năng có khả năng độc lập triển khai tính năng sản phẩm.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000017",
			Title:          "Cyber Security Specialist (SOC / Pentest)",
			Department:     "Security",
			Level:          "senior",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      26000000,
			SalaryMax:      48000000,
			Currency:       "VND",
			Description:    "Đánh giá lỗ hổng bảo mật Web/API (Pentest), giám sát an toàn thông tin hệ thống và tuân thủ tiêu chuẩn ISO 27001.",
			Requirements:   "3+ năm kinh nghiệm Pentest/SOC, có chứng chỉ CEH, OSCP hoặc CISSP. Am hiểu OWASP Top 10 và Security Hardening.",
			Benefits:       "Phụ cấp trách nhiệm an ninh mạng, tài trợ toàn bộ chi phí thi chứng chỉ quốc tế.",
			Status:         "open",
			AISummary:      "Chuyên gia Chuyên gia Bảo mật thông tin có chứng chỉ quốc tế bảo vệ nền tảng.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000018",
			Title:          "Business Analyst (IT Banking & Fintech)",
			Department:     "Business Analysis",
			Level:          "senior",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      24000000,
			SalaryMax:      40000000,
			Currency:       "VND",
			Description:    "Thu thập yêu cầu nghiệp vụ từ khách hàng Doanh nghiệp, viết tài liệu SRS/BRD, vẽ luồng công việc (BPMN) cho team Dev.",
			Requirements:   "3+ năm kinh nghiệm IT BA trong lĩnh vực Fintech/SaaS. Kỹ năng giao tiếp và viết tài liệu kỹ thuật xuất sắc.",
			Benefits:       "Lương tháng 14, chế độ bảo hiểm cao cấp cho bản thân và người thân.",
			Status:         "open",
			AISummary:      "Business Analyst Senior cầu nối chuẩn xác giữa nghiệp vụ doanh nghiệp và kỹ thuật.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000019",
			Title:          "Digital Marketing Manager (Growth & Performance)",
			Department:     "Marketing",
			Level:          "lead",
			Location:       "TP. Hồ Chí Minh",
			EmploymentType: "full_time",
			SalaryMin:      25000000,
			SalaryMax:      45000000,
			Currency:       "VND",
			Description:    "Lập chiến lược Marketing tổng thể, tối ưu chi phí quảng cáo (FB Ads, Google Ads, LinkedIn Ads) và kéo lead ứng viên/nhà tuyển dụng.",
			Requirements:   "4+ năm kinh nghiệm Performance Marketing cho các ứng dụng Tech/SaaS. Quản lý ngân sách > 500 triệu/tháng.",
			Benefits:       "Thưởng theo phần trăm doanh thu tăng trưởng, du lịch nước ngoài.",
			Status:         "open",
			AISummary:      "Marketing Lead có thành tích thực chiến tăng trưởng người dùng B2B/B2C.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000020",
			Title:          "Senior iOS Developer (SwiftUI)",
			Department:     "Engineering",
			Level:          "senior",
			Location:       "TP. Hồ Chí Minh",
			EmploymentType: "full_time",
			SalaryMin:      30000000,
			SalaryMax:      52000000,
			Currency:       "VND",
			Description:    "Phát triển ứng dụng iOS native nâng cao với Swift & SwiftUI, tối ưu hiệu năng render video phỏng vấn và ghi âm AI.",
			Requirements:   "4+ năm kinh nghiệm iOS native, giỏi Swift, Combine, CoreData, AVFoundation. Đã phát triển ứng dụng xếp hạng cao trên App Store.",
			Benefits:       "Cấp mới iPhone 15 Pro & Macbook Pro M3, môi trường làm việc chuẩn quốc tế.",
			Status:         "open",
			AISummary:      "Lập trình viên iOS Native Senior chuyên sâu xử lý Audio/Video trên Apple Ecosystem.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000021",
			Title:          "Senior Android Engineer (Kotlin)",
			Department:     "Engineering",
			Level:          "senior",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      28000000,
			SalaryMax:      48000000,
			Currency:       "VND",
			Description:    "Xây dựng ứng dụng Android Native bằng Kotlin, Jetpack Compose, Coroutines và Clean Architecture.",
			Requirements:   "4+ năm kinh nghiệm Android Native, thành thạo Kotlin, Dagger-Hilt, Room, Retrofit. Hiểu rõ quy trình release Play Store.",
			Benefits:       "Thưởng dự án theo từng bản phát hành, phụ cấp ăn trưa và gửi xe.",
			Status:         "open",
			AISummary:      "Kỹ sư Android Senior thành thạo Kotlin Jetpack Compose hiện đại.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000022",
			Title:          "Cloud Solutions Architect (GCP / Azure)",
			Department:     "Infrastructure",
			Level:          "lead",
			Location:       "Remote",
			EmploymentType: "full_time",
			SalaryMin:      50000000,
			SalaryMax:      90000000,
			Currency:       "VND",
			Description:    "Thiết kế tổng thể kiến trúc đám mây đa hạ tầng Multi-cloud, tối ưu hóa chi phí vận hành Cloud và xây dựng quy chuẩn bảo mật.",
			Requirements:   "6+ năm kinh nghiệm Cloud Architecture, sở hữu chứng chỉ GCP Professional Cloud Architect hoặc AWS Solutions Architect Professional.",
			Benefits:       "Lương thu nhập cực cao, quyền mua cổ phiếu ưu đãi, hợp đồng dài hạn.",
			Status:         "open",
			AISummary:      "Kiến trúc sư giải pháp Đám mây cấp cao định hướng chiến lược hạ tầng.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000023",
			Title:          "PHP / Laravel Senior Developer",
			Department:     "Engineering",
			Level:          "senior",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      20000000,
			SalaryMax:      35000000,
			Currency:       "VND",
			Description:    "Bảo trì và mở rộng hệ thống Portal quản lý tuyển dụng cũ sang kiến trúc mới bằng Laravel 10 và MySQL.",
			Requirements:   "3+ năm kinh nghiệm Laravel, MySQL, Redis, RESTful API. Có tư duy refactor code sạch và biết sử dụng Docker.",
			Benefits:       "Lương tháng 13++, làm việc từ thứ 2 đến thứ 6, nghỉ phép 14 ngày/năm.",
			Status:         "open",
			AISummary:      "Lập trình viên Laravel Senior vững tay nghề xử lý cơ sở dữ liệu quan hệ.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000024",
			Title:          "Intern Frontend Developer (Vue / React)",
			Department:     "Engineering",
			Level:          "intern",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      5000000,
			SalaryMax:      8000000,
			Currency:       "VND",
			Description:    "Thực tập sinh Frontend được tham gia dự án thực tế, viết giao diện bằng Vue 3 / ReactJS dưới sự hướng dẫn của Senior Mentor.",
			Requirements:   "Sinh viên năm cuối hoặc mới tốt nghiệp chuyên ngành IT. Nắm chắc cơ bản HTML, CSS, JavaScript ES6.",
			Benefits:       "Trợ cấp thực tập hàng tháng, cơ hội cất cân lên chính thức sau 3 tháng.",
			Status:         "open",
			AISummary:      "Thực tập sinh Frontend có tư duy học hỏi nhanh và nền tảng lập trình web tốt.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000025",
			Title:          "Intern Backend Developer (Golang)",
			Department:     "Engineering",
			Level:          "intern",
			Location:       "TP. Hồ Chí Minh",
			EmploymentType: "full_time",
			SalaryMin:      6000000,
			SalaryMax:      9000000,
			Currency:       "VND",
			Description:    "Thực tập viết API RESTful đơn giản bằng Golang, viết Unit Test và hỗ trợ team vận hành cơ sở dữ liệu PostgreSQL.",
			Requirements:   "Yêu thích ngôn ngữ Go, có kiến thức về SQL và lập trình hướng đối tượng. Tinh thần trách nhiệm cao.",
			Benefits:       "Phụ cấp ăn trưa, lộ trình thăng tiến rõ ràng thành Junior Engineer.",
			Status:         "open",
			AISummary:      "Thực tập sinh Golang tiềm năng có đam mê phát triển hệ thống Backend.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000026",
			Title:          "Scrum Master & Agile Coach",
			Department:     "Project Management",
			Level:          "middle",
			Location:       "TP. Hồ Chí Minh",
			EmploymentType: "full_time",
			SalaryMin:      28000000,
			SalaryMax:      48000000,
			Currency:       "VND",
			Description:    "Điều phối các buổi Daily Standup, Sprint Planning, Retrospective cho 3 team phát triển phần mềm theo mô hình Agile/Scrum.",
			Requirements:   "2+ năm kinh nghiệm Scrum Master, có chứng chỉ PSM I / CSM. Kỹ năng giải quyết xung đột và thúc đẩy hiệu suất team.",
			Benefits:       "Gói chăm sóc sức khỏe gia đình cao cấp, tham gia các khóa huấn luyện lãnh đạo.",
			Status:         "open",
			AISummary:      "Scrum Master chuyên nghiệp giúp tối ưu quy trình phát triển Agile.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000027",
			Title:          "Content Marketing & Copywriter Specialist",
			Department:     "Marketing",
			Level:          "junior",
			Location:       "Đà Nẵng",
			EmploymentType: "full_time",
			SalaryMin:      10000000,
			SalaryMax:      17000000,
			Currency:       "VND",
			Description:    "Sáng tạo nội dung bài viết Fanpage, Blog SEO, Email Marketing truyền tải thông điệp ứng dụng tuyển dụng AI thu hút người dùng.",
			Requirements:   "1+ năm kinh nghiệm viết Content Marketing, văn phong đa dạng. Biết tư duy SEO cơ bản và thiết kế Canva đơn giản.",
			Benefits:       "Môi trường làm việc trẻ trung 9x/2k, teambuilding định kỳ.",
			Status:         "open",
			AISummary:      "Copywriter trẻ sáng tạo có khả năng truyền tải thông điệp sản phẩm công nghệ.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000028",
			Title:          "Embedded Firmware Engineer (C/C++ & IoT)",
			Department:     "Hardware & Embedded",
			Level:          "senior",
			Location:       "Đà Nẵng",
			EmploymentType: "full_time",
			SalaryMin:      22000000,
			SalaryMax:      38000000,
			Currency:       "VND",
			Description:    "Lập trình nhúng vi điều khiển ARM Cortex, ESP32, giao thức UART/SPI/I2C/BLE cho các thiết bị phần cứng thông minh.",
			Requirements:   "3+ năm kinh nghiệm C/C++ nhúng, đọc hiểu sơ đồ mạch điện tử. Biết FreeRTOS là một lợi thế lớn.",
			Benefits:       "Phòng Lab phần cứng hiện đại, thưởng sáng chế thiết bị.",
			Status:         "open",
			AISummary:      "Kỹ sư Lập trình nhúng Senior làm chủ vi điều khiển và thiết bị IoT.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000029",
			Title:          "Blockchain & Smart Contract Developer",
			Department:     "Innovation & Web3",
			Level:          "senior",
			Location:       "Remote",
			EmploymentType: "full_time",
			SalaryMin:      45000000,
			SalaryMax:      85000000,
			Currency:       "VND",
			Description:    "Phát triển Smart Contract bằng Solidity trên Ethereum/Polygon phục vụ tính năng xác thực bằng cấp CV chống giả mạo.",
			Requirements:   "3+ năm kinh nghiệm Web3/Blockchain, thành thạo Solidity, Hardhat, Ethers.js. Hiểu biết về Security Audit Smart Contract.",
			Benefits:       "Chi trả lương linh hoạt bằng USDT/VND, làm việc remote toàn cầu.",
			Status:         "open",
			AISummary:      "Lập trình viên Blockchain chuyên sâu Smart Contract và ứng dụng Web3.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000030",
			Title:          "Sales B2B Executive (Enterprise Software)",
			Department:     "Sales & Business Development",
			Level:          "middle",
			Location:       "TP. Hồ Chí Minh",
			EmploymentType: "full_time",
			SalaryMin:      15000000,
			SalaryMax:      40000000,
			Currency:       "VND",
			Description:    "Tìm kiếm và tiếp cận các Doanh nghiệp, Tập đoàn lớn để giới thiệu và chốt hợp đồng bản quyền giải pháp Tuyển dụng AI.",
			Requirements:   "2+ năm kinh nghiệm Sales B2B phần mềm/Dịch vụ Doanh nghiệp. Kỹ năng đàm phán, thuyết trình tốt.",
			Benefits:       "Hoa hồng chốt hợp đồng không giới hạn, phụ cấp xăng xe tiếp khách.",
			Status:         "open",
			AISummary:      "Chuyên viên Kinh doanh B2B bản lĩnh với khả năng mang lại doanh thu lớn.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000031",
			Title:          "Technical Support Engineer (L2/L3)",
			Department:     "Customer Success",
			Level:          "middle",
			Location:       "Cần Thơ",
			EmploymentType: "full_time",
			SalaryMin:      12000000,
			SalaryMax:      18000000,
			Currency:       "VND",
			Description:    "Hỗ trợ kỹ thuật cấp cao cho khách hàng Doanh nghiệp khi sử dụng hệ thống phỏng vấn AI, tra cứu log và hỗ trợ khắc phục sự cố.",
			Requirements:   "1-2 năm kinh nghiệm Tech Support hoặc System Admin. Đọc hiểu log API, truy vấn SQL cơ bản.",
			Benefits:       "Thưởng hỗ trợ khách hàng đạt CSAT cao, môi trường văn phòng thân thiện.",
			Status:         "open",
			AISummary:      "Kỹ sư Hỗ trợ kỹ thuật tận tâm với kỹ năng xử lý sự cố nhanh chóng.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000032",
			Title:          "HRBP & Talent Acquisition Lead",
			Department:     "Human Resources",
			Level:          "lead",
			Location:       "TP. Hồ Chí Minh",
			EmploymentType: "full_time",
			SalaryMin:      25000000,
			SalaryMax:      42000000,
			Currency:       "VND",
			Description:    "Xây dựng chiến lược thu hút nhân tài IT cho công ty, trực tiếp vận hành hệ thống tuyển dụng AI nội bộ.",
			Requirements:   "4+ năm kinh nghiệm Recruitment Lead / HRBP ngành IT Tech. Có mạng lưới quan hệ ứng viên rộng mở.",
			Benefits:       "Lương tháng 13, thưởng Quý, chế độ đãi ngộ hàng đầu.",
			Status:         "open",
			AISummary:      "Trưởng nhóm Tuyển dụng HRBP am hiểu thị trường nhân sự công nghệ.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000033",
			Title:          "System Administrator (Linux & Network)",
			Department:     "Infrastructure",
			Level:          "middle",
			Location:       "Hải Phòng",
			EmploymentType: "full_time",
			SalaryMin:      14000000,
			SalaryMax:      22000000,
			Currency:       "VND",
			Description:    "Quản trị hệ thống máy chủ Linux (Ubuntu/CentOS), cấu hình Firewall, Nginx Reverse Proxy và hệ thống sao lưu dữ liệu.",
			Requirements:   "2+ năm kinh nghiệm Linux SysAdmin, nắm vững TCP/IP, DNS, VPN, SSL. Có chứng chỉ CCNA/LPIC-1.",
			Benefits:       "Phụ cấp trực ca khẩn cấp, bảo hiểm chăm sóc sức khỏe.",
			Status:         "open",
			AISummary:      "Quản trị viên Hệ thống Linux tận tụy đảm bảo máy chủ vận hành 24/7.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000034",
			Title:          "Technical Writer & API Documentation",
			Department:     "Product",
			Level:          "middle",
			Location:       "Remote",
			EmploymentType: "full_time",
			SalaryMin:      15000000,
			SalaryMax:      26000000,
			Currency:       "VND",
			Description:    "Soạn thảo tài liệu hướng dẫn tích hợp API, tài liệu kiến trúc hệ thống và User Guide cho nhà phát triển.",
			Requirements:   "2+ năm kinh nghiệm Technical Writing, tiếng Anh đọc viết thành thạo (IELTS >= 7.0 hoặc tương đương). Biết Swagger/Postman.",
			Benefits:       "Làm việc Remote hoàn toàn, thời gian chủ động.",
			Status:         "open",
			AISummary:      "Technical Writer có khả năng diễn đạt kiến thức kỹ thuật phức tạp thành tài liệu dễ hiểu.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000035",
			Title:          "Graphic Designer & Motion Video Artist",
			Department:     "Marketing",
			Level:          "middle",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      14000000,
			SalaryMax:      24000000,
			Currency:       "VND",
			Description:    "Thiết kế banner quảng cáo, dựng video ngắn 2D/Motion Graphics giới thiệu tính năng phỏng vấn AI cho các kênh truyền thông.",
			Requirements:   "2+ năm kinh nghiệm Graphic & Motion Design. Thành thạo After Effects, Premiere, Illustrator, Photoshop.",
			Benefits:       "Máy tính đồ họa cấu hình khủng, thưởng theo độ phủ chiến dịch.",
			Status:         "open",
			AISummary:      "Graphic & Motion Artist tạo ra các ấn phẩm truyền thông hình ảnh ấn tượng.",
		},
		{
			ID:             "cccccccc-0000-0000-0000-000000000036",
			Title:          "Chief Technology Officer (CTO)",
			Department:     "Executive Board",
			Level:          "lead",
			Location:       "Hà Nội",
			EmploymentType: "full_time",
			SalaryMin:      80000000,
			SalaryMax:      150000000,
			Currency:       "VND",
			Description:    "Lãnh đạo toàn bộ khối Công nghệ & AI, định hướng chiến lược kiến trúc phần mềm, bảo mật và phát triển đội ngũ kỹ sư 100+ người.",
			Requirements:   "8+ năm vị trí quản lý kỹ thuật cấp cao (VP of Engineering / CTO) tại các công ty Công nghệ lớn. Tầm nhìn chiến lược công nghệ vượt trội.",
			Benefits:       "Gói cổ phần ESOP lớn, xe đưa đón, ngân sách tự quyết khối công nghệ.",
			Status:         "open",
			AISummary:      "Giám đốc Công nghệ CTO tầm vóc lãnh đạo toàn diện chiến lược kỹ thuật công ty.",
		},
	}

	stmt, err := db.Prepare(`
		INSERT INTO jobs (id, company_id, title, department, level, location, employment_type,
		                  salary_min, salary_max, currency, description, requirements, benefits, status,
		                  ai_summary, created_by)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
		ON CONFLICT (id) DO UPDATE SET
			title = EXCLUDED.title,
			department = EXCLUDED.department,
			level = EXCLUDED.level,
			location = EXCLUDED.location,
			employment_type = EXCLUDED.employment_type,
			salary_min = EXCLUDED.salary_min,
			salary_max = EXCLUDED.salary_max,
			currency = EXCLUDED.currency,
			description = EXCLUDED.description,
			requirements = EXCLUDED.requirements,
			benefits = EXCLUDED.benefits,
			status = EXCLUDED.status,
			ai_summary = EXCLUDED.ai_summary;
	`)
	if err != nil {
		log.Fatalf("Failed to prepare statement: %v", err)
	}
	defer stmt.Close()

	count := 0
	for _, j := range jobs {
		_, err := stmt.Exec(
			j.ID, companyID, j.Title, j.Department, j.Level, j.Location, j.EmploymentType,
			j.SalaryMin, j.SalaryMax, j.Currency, j.Description, j.Requirements, j.Benefits, j.Status,
			j.AISummary, createdBy,
		)
		if err != nil {
			log.Printf("Failed to insert job %s: %v", j.Title, err)
		} else {
			count++
		}
	}

	fmt.Printf("Successfully inserted/updated %d diverse jobs into Supabase PostgreSQL DB!\n", count)
}
