package middleware

// contextKey is an unexported type for context keys in this package.
// Using a named type prevents collisions with keys defined by other packages.
type contextKey string

const (
	// CtxUserID is the context key for the authenticated user's UUID string.
	CtxUserID contextKey = "user_id"

	// CtxUserRole is the context key for the authenticated user's role string.
	CtxUserRole contextKey = "user_role"

	// CtxCompanyID is the context key for the company UUID resolved by
	// CompanyScopeMiddleware from the {company_id} URL parameter.
	CtxCompanyID contextKey = "company_id"

	// CtxRequestID is the context key for the per-request UUID generated by
	// AuthMiddleware and echoed in every response envelope.
	CtxRequestID contextKey = "request_id"

	// CtxCompanyRole is the context key for the authenticated user's role in the company.
	CtxCompanyRole contextKey = "company_role"
)
